#if !canImport(ObjectiveC)
import XCTest

extension DirectionalNeighborsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DirectionalNeighborsTests = [
        ("testManyOccupiedSeats", testManyOccupiedSeats),
        ("testNoVisibleOccupiedSeats", testNoVisibleOccupiedSeats),
        ("testOneEmptySeat", testOneEmptySeat),
        ("testOnlyOneVisibleSeat", testOnlyOneVisibleSeat),
    ]
}

extension NumericsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__NumericsTests = [
        ("testFactoring", testFactoring),
        ("testFactoringStartingAt", testFactoringStartingAt),
    ]
}

extension Year2015Day10Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Year2015Day10Tests = [
        ("testPart1", testPart1),
        ("testPart2", testPart2),
    ]
}

extension Year2015Day11Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Year2015Day11Tests = [
        ("testPart1", testPart1),
        ("testPart2", testPart2),
    ]
}

extension Year2015Day12Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Year2015Day12Tests = [
        ("testPart1", testPart1),
        ("testPart2", testPart2),
    ]
}

extension Year2015Day13Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Year2015Day13Tests = [
        ("testExample1", testExample1),
        ("testPart1", testPart1),
        ("testPart2", testPart2),
    ]
}

extension Year2015Day14Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Year2015Day14Tests = [
        ("testExample1", testExample1),
        ("testExample2", testExample2),
        ("testPart1", testPart1),
        ("testPart2", testPart2),
    ]
}

extension Year2015Day15Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Year2015Day15Tests = [
        ("testExample1", testExample1),
        ("testExample2", testExample2),
        ("testPart1", testPart1),
        ("testPart2", testPart2),
    ]
}

extension Year2015Day16Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Year2015Day16Tests = [
        ("testPart1", testPart1),
        ("testPart2", testPart2),
    ]
}

extension Year2015Day17Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Year2015Day17Tests = [
        ("testExample1", testExample1),
        ("testExample2", testExample2),
        ("testPart1", testPart1),
        ("testPart2", testPart2),
    ]
}

extension Year2015Day18Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Year2015Day18Tests = [
        ("testExample1", testExample1),
        ("testExample2", testExample2),
        ("testPart1", testPart1),
        ("testPart2", testPart2),
    ]
}

extension Year2015Day19Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Year2015Day19Tests = [
        ("testExample1", testExample1),
        ("testExample2", testExample2),
        ("testPart1", testPart1),
        ("testPart2", testPart2),
    ]
}

extension Year2015Day1Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Year2015Day1Tests = [
        ("testPart1", testPart1),
        ("testPart2", testPart2),
    ]
}

extension Year2015Day20Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Year2015Day20Tests = [
        ("testExample1", testExample1),
        ("testPart1", testPart1),
        ("testPart2", testPart2),
    ]
}

extension Year2015Day21Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Year2015Day21Tests = [
        ("testPart1", testPart1),
        ("testPart2", testPart2),
    ]
}

extension Year2015Day22Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Year2015Day22Tests = [
        ("testExample1", testExample1),
        ("testExample2", testExample2),
        ("testPart1", testPart1),
        ("testPart2", testPart2),
    ]
}

extension Year2015Day23Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Year2015Day23Tests = [
        ("testExample1", testExample1),
        ("testPart1", testPart1),
        ("testPart2", testPart2),
    ]
}

extension Year2015Day24Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Year2015Day24Tests = [
        ("testExample1", testExample1),
        ("testExample2", testExample2),
        ("testPart1", testPart1),
        ("testPart2", testPart2),
    ]
}

extension Year2015Day25Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Year2015Day25Tests = [
        ("testPart1", testPart1),
        ("testPart2", testPart2),
    ]
}

extension Year2015Day2Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Year2015Day2Tests = [
        ("testPart1", testPart1),
        ("testPart2", testPart2),
    ]
}

extension Year2015Day3Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Year2015Day3Tests = [
        ("testPart1", testPart1),
        ("testPart2", testPart2),
    ]
}

extension Year2015Day4Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Year2015Day4Tests = [
        ("testExample1", testExample1),
        ("testExample2", testExample2),
        ("testPart1", testPart1),
        ("testPart2", testPart2),
    ]
}

extension Year2015Day5Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Year2015Day5Tests = [
        ("testPart1", testPart1),
        ("testPart2", testPart2),
    ]
}

extension Year2015Day6Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Year2015Day6Tests = [
        ("testPart1", testPart1),
        ("testPart2", testPart2),
    ]
}

extension Year2015Day7Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Year2015Day7Tests = [
        ("testExample1", testExample1),
        ("testPart1", testPart1),
        ("testPart2", testPart2),
    ]
}

extension Year2015Day8Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Year2015Day8Tests = [
        ("testExample1", testExample1),
        ("testExample2", testExample2),
        ("testPart1", testPart1),
        ("testPart2", testPart2),
    ]
}

extension Year2015Day9Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Year2015Day9Tests = [
        ("testExample1", testExample1),
        ("testExample2", testExample2),
        ("testPart1", testPart1),
        ("testPart2", testPart2),
    ]
}

extension Year2016Day1Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Year2016Day1Tests = [
        ("testExample1", testExample1),
        ("testExample2", testExample2),
        ("testPart1", testPart1),
        ("testPart2", testPart2),
    ]
}

extension Year2016Day2Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Year2016Day2Tests = [
        ("testExample1", testExample1),
        ("testExample2", testExample2),
        ("testPart1", testPart1),
        ("testPart2", testPart2),
    ]
}

extension Year2016Day3Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Year2016Day3Tests = [
        ("testPart1", testPart1),
        ("testPart2", testPart2),
    ]
}

extension Year2016Day4Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Year2016Day4Tests = [
        ("testExample1", testExample1),
        ("testExample2", testExample2),
        ("testPart1", testPart1),
        ("testPart2", testPart2),
    ]
}

extension Year2016Day5Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Year2016Day5Tests = [
        ("testExample1", testExample1),
        ("testExample2", testExample2),
        ("testPart1", testPart1),
        ("testPart2", testPart2),
    ]
}

extension Year2020Day10Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Year2020Day10Tests = [
        ("testExample1", testExample1),
        ("testExample1Part2", testExample1Part2),
        ("testExample2", testExample2),
        ("testExample2Part2", testExample2Part2),
        ("testPart1", testPart1),
        ("testPart2", testPart2),
    ]
}

extension Year2020Day11Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Year2020Day11Tests = [
        ("testExample1", testExample1),
        ("testExample2", testExample2),
        ("testPart1", testPart1),
        ("testPart2", testPart2),
    ]
}

extension Year2020Day12Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Year2020Day12Tests = [
        ("testExample1", testExample1),
        ("testExample2", testExample2),
        ("testPart1", testPart1),
        ("testPart2", testPart2),
    ]
}

extension Year2020Day13Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Year2020Day13Tests = [
        ("testExample1", testExample1),
        ("testExample2", testExample2),
        ("testPart1", testPart1),
        ("testPart2", testPart2),
    ]
}

extension Year2020Day14Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Year2020Day14Tests = [
        ("testExample1", testExample1),
        ("testExample2", testExample2),
        ("testPart1", testPart1),
        ("testPart2", testPart2),
    ]
}

extension Year2020Day15Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Year2020Day15Tests = [
        ("testExample1", testExample1),
        ("testExample2", testExample2),
        ("testPart1", testPart1),
        ("testPart2", testPart2),
    ]
}

extension Year2020Day1Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Year2020Day1Tests = [
        ("testExample1", testExample1),
        ("testExample2", testExample2),
        ("testPart1", testPart1),
        ("testPart2", testPart2),
    ]
}

extension Year2020Day2Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Year2020Day2Tests = [
        ("testExample1", testExample1),
        ("testExample2", testExample2),
        ("testPart1", testPart1),
        ("testPart2", testPart2),
    ]
}

extension Year2020Day3Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Year2020Day3Tests = [
        ("testExample1", testExample1),
        ("testExample2", testExample2),
        ("testPart1", testPart1),
        ("testPart2", testPart2),
    ]
}

extension Year2020Day4Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Year2020Day4Tests = [
        ("testExample1", testExample1),
        ("testPart1", testPart1),
        ("testPart2", testPart2),
    ]
}

extension Year2020Day5Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Year2020Day5Tests = [
        ("testExample1", testExample1),
        ("testPart1", testPart1),
        ("testPart2", testPart2),
    ]
}

extension Year2020Day6Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Year2020Day6Tests = [
        ("testExample1", testExample1),
        ("testExample2", testExample2),
        ("testPart1", testPart1),
        ("testPart2", testPart2),
    ]
}

extension Year2020Day7Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Year2020Day7Tests = [
        ("testExample1", testExample1),
        ("testExample2", testExample2),
        ("testPart1", testPart1),
        ("testPart2", testPart2),
    ]
}

extension Year2020Day8Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Year2020Day8Tests = [
        ("testExample1", testExample1),
        ("testExample2", testExample2),
        ("testPart1", testPart1),
        ("testPart2", testPart2),
    ]
}

extension Year2020Day9Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Year2020Day9Tests = [
        ("testExample1", testExample1),
        ("testExample2", testExample2),
        ("testPart1", testPart1),
        ("testPart2", testPart2),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(DirectionalNeighborsTests.__allTests__DirectionalNeighborsTests),
        testCase(NumericsTests.__allTests__NumericsTests),
        testCase(Year2015Day10Tests.__allTests__Year2015Day10Tests),
        testCase(Year2015Day11Tests.__allTests__Year2015Day11Tests),
        testCase(Year2015Day12Tests.__allTests__Year2015Day12Tests),
        testCase(Year2015Day13Tests.__allTests__Year2015Day13Tests),
        testCase(Year2015Day14Tests.__allTests__Year2015Day14Tests),
        testCase(Year2015Day15Tests.__allTests__Year2015Day15Tests),
        testCase(Year2015Day16Tests.__allTests__Year2015Day16Tests),
        testCase(Year2015Day17Tests.__allTests__Year2015Day17Tests),
        testCase(Year2015Day18Tests.__allTests__Year2015Day18Tests),
        testCase(Year2015Day19Tests.__allTests__Year2015Day19Tests),
        testCase(Year2015Day1Tests.__allTests__Year2015Day1Tests),
        testCase(Year2015Day20Tests.__allTests__Year2015Day20Tests),
        testCase(Year2015Day21Tests.__allTests__Year2015Day21Tests),
        testCase(Year2015Day22Tests.__allTests__Year2015Day22Tests),
        testCase(Year2015Day23Tests.__allTests__Year2015Day23Tests),
        testCase(Year2015Day24Tests.__allTests__Year2015Day24Tests),
        testCase(Year2015Day25Tests.__allTests__Year2015Day25Tests),
        testCase(Year2015Day2Tests.__allTests__Year2015Day2Tests),
        testCase(Year2015Day3Tests.__allTests__Year2015Day3Tests),
        testCase(Year2015Day4Tests.__allTests__Year2015Day4Tests),
        testCase(Year2015Day5Tests.__allTests__Year2015Day5Tests),
        testCase(Year2015Day6Tests.__allTests__Year2015Day6Tests),
        testCase(Year2015Day7Tests.__allTests__Year2015Day7Tests),
        testCase(Year2015Day8Tests.__allTests__Year2015Day8Tests),
        testCase(Year2015Day9Tests.__allTests__Year2015Day9Tests),
        testCase(Year2016Day1Tests.__allTests__Year2016Day1Tests),
        testCase(Year2016Day2Tests.__allTests__Year2016Day2Tests),
        testCase(Year2016Day3Tests.__allTests__Year2016Day3Tests),
        testCase(Year2016Day4Tests.__allTests__Year2016Day4Tests),
        testCase(Year2016Day5Tests.__allTests__Year2016Day5Tests),
        testCase(Year2020Day10Tests.__allTests__Year2020Day10Tests),
        testCase(Year2020Day11Tests.__allTests__Year2020Day11Tests),
        testCase(Year2020Day12Tests.__allTests__Year2020Day12Tests),
        testCase(Year2020Day13Tests.__allTests__Year2020Day13Tests),
        testCase(Year2020Day14Tests.__allTests__Year2020Day14Tests),
        testCase(Year2020Day15Tests.__allTests__Year2020Day15Tests),
        testCase(Year2020Day1Tests.__allTests__Year2020Day1Tests),
        testCase(Year2020Day2Tests.__allTests__Year2020Day2Tests),
        testCase(Year2020Day3Tests.__allTests__Year2020Day3Tests),
        testCase(Year2020Day4Tests.__allTests__Year2020Day4Tests),
        testCase(Year2020Day5Tests.__allTests__Year2020Day5Tests),
        testCase(Year2020Day6Tests.__allTests__Year2020Day6Tests),
        testCase(Year2020Day7Tests.__allTests__Year2020Day7Tests),
        testCase(Year2020Day8Tests.__allTests__Year2020Day8Tests),
        testCase(Year2020Day9Tests.__allTests__Year2020Day9Tests),
    ]
}
#endif
